### ISSUE TITLE
Issue: Connection Timeout do not await when connection server is not running.

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#10]
As discussed, looks like we have issue with method:

`cfg.setConnectTimeoutMillis();`

that do not await when trying to connect to "offline" server

**Comment by tlf30** [comment]
This looks relevant: https://stackoverflow.com/questions/46614123/netty-client-takes-very-long-before-broken-network-is-detected

**Comment by oxplay2** [comment]
Hmm... but i suppose it refer only when server have connection with client?

while here we have a lot exceptions in 1 second, just because it loop connection try while server is "off"

**Comment by tlf30** [comment]
Yes, I will work on something a little cleaner than the attached stackoverflow solution. 
I am thinking like a custom timeout handler with our own heartbeat from the server periodically, perhaps the heartbeat period can be configurable.

**Comment by oxplay2** [comment]
im not sure if we think about same issue.

**Comment by oxplay2** [comment]
i think the only change here needed would be "custom timeout" but only for "reconnect" functionality, the other should use Netty default method.

**Comment by tlf30** [comment]
Tagging internal issue: https://git.liquidcrystalstudios.com/outside/outside/-/issues/201
