### ISSUE TITLE
Feature: Github packages

### ISSUE THREAD

**Issue by tlf30** [tlf30/monkey-netty#13]
Need to configure github based packages.
https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-gradle

**Comment by oxplay2** [comment]
See commit comment,

i belive all is fine, but if something will be missing, its worth look at Stephen's Minie example:
https://github.com/stephengold/Minie/blob/master/MinieLibrary/build.gradle

**Comment by tlf30** [comment]
That is interesting that he added the license. I will look into that.
I am very familiar with how GitLab handles CI, packages, and deployment because my company has an in house GitLab server, but GitHub is a learning curve for me. It may take me a couple attempts to get it right, but I think it will be much nicer than trying to deploy to bintray (I have had nothing but issues with artifacts deployed to bintray)

If only it was as easy as GitLab. Someday it may get there (or maybe it is there and I just need to catch up :P).

**Comment by oxplay2** [comment]
same here(but not GitLab), also Nexus as artifacts proxy.

myself i also dont know many things about Github. But, we learn :)

Anyway, all is fine if this works, just linked Stephen's solution if you would see something interesting.

**Comment by tlf30** [comment]
I just got done testing this for v0.1.0 on a private repo. It works good. I made a couple changes in #25 . Closing.
