### ISSUE TITLE
Feature: Re-Implement "ctx.channel().attr(key)" into MN wrapper interface NetworkClient

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#17]
Why needed? - Could easly add custom connection data without extending default NettyClient class.

We cant access ctx, since UDP dont provide ctx.

But still we should add attribute functionality for Connection.

We could just extend NetworkClient interface by "attr" methods.

not important, but writing this "issue topic" for future. 
(i am anyway waiting you to reply in Question issue first anyway, so later i could create PR myself)

**Comment by tlf30** [comment]
Yes, I think this would be good to bring into the wrapper, I actually did not realize that it was not part of it. I just checked the version in the Outside Engine, and atts is also not part of its abstract interface either. This was an oversight on my part, and it should be part of the NetworkClient interface.

**Comment by oxplay2** [comment]
indeed.

its to avoid "upper casting"(that is slow comparing to down-casting) like:

((NettyConnection)client).setAttribute(

and people would not know they can use it via casting. while adding to interface they just ctrl-space and see it in interface.

so it would help much.

i assume we dont need Client provide setAttribute for itself? 
but also assume its not problem for client have methods to set attributes for itself.(just not needed code)

or we could jsut throw exception "unsupported method" for client setAttribute itself. Only server NettyConnection really need it.

**Comment by tlf30** [comment]
I think it would be fine to put in both. That way it is consistent, and if someone wants to use it on the Client side, then it is available (even though there are probably better places to put attribute data Client side in a correctly built client application)

**Comment by oxplay2** [comment]
added PR https://github.com/tlf30/monkey-netty/pull/18

its small change. Not tested ir yet, but its same code as in NettyConnection so should work fine.
