### ISSUE TITLE
Issue: server.onConnect() is called after server.onMessage() for TCP when client sent messages in own client.onConnect()

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#20]
Hi,

i have noticed that somehow it is possible to send messages before server trigger onConnect for a client.

even when i added isConnected() into "onMessage" in server, it return true before onConnect is executed.

Worth to investigate.

i had order:

Client onConnect (it send message onConnect)
Server onMessage (receive that message)
Server onConnect (now it execute onConnect) - wrong, should be before onMessage

to replicate add to Client:

        client.registerListener(new ConnectionListener() {
            @Override
            public void onConnect(NetworkClient client) {
                System.out.println("Client: Connected to Server");
                client.send(new TestTCPMessage());
                client.send(new TestUDPMessage());
            }

            @Override
            public void onDisconnect(NetworkClient client) {

            }
        });

Note TCP is before onConnect, while UDP is after.

> Got message Test TCP Message from client /127.0.0.1:43308
> io.tlf.monkeynetty.test.messages.TestTCPMessage@285a3254
> ...
> Client connected: /127.0.0.1:43308
> ...
> Got message Test UDP Message from client /127.0.0.1:43308
> io.tlf.monkeynetty.test.messages.TestUDPMessage@9bb8f0b

both TCP and UDP messages should be sent after serverConnectionListener.onConnect  (server side one)

**IMO its important issue, since onMessage should never be called before onConnect**

**Comment by tlf30** [comment]
Oh, that is a good catch. I have not seen this on outside, but I think it could have the same issue. 
I will investigate.

**Comment by tlf30** [comment]
Tagging internal issue:
https://git.liquidcrystalstudios.com/outside/outside/-/issues/188

**Comment by tlf30** [comment]
@oxplay2 I have submitted a pull request, can you please review?
