### ISSUE TITLE
Tracking Netty issue 344

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#3]
Just to remember:

Based on HUB topic https://hub.jmonkeyengine.org/t/monkey-netty-server-client-communication-system-for-jme-using-netty-io/43860/3

In future, Monkey-Netty seems will need a little UDP rebuild using Netty solution.

But first require Netty to solve issue

https://github.com/netty/netty/issues/344#issuecomment-625847691

**Comment by tlf30** [comment]
Netty closed their issue with won't fix
