### ISSUE TITLE
Feature: Optimization

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#4]
I were thinking about it earlier, before even using Monkey-Netty.

The Netty.io ObjectEncoder / ObjectDecoder have one optimize issue.

try add above current p.addLast(:

`p.addLast("logger", new LoggingHandler(LogLevel.INFO));`

And look at Logger data package.
**You will find out that Netty send full class names(for message class and all classes inside it - fields)**
Im not sure if UDP have this issue too, but i assume yes, because DatagramPacketObjectDecoder is using:

`private final ObjectDecoder delegateDecoder;`

**so i belive both UDP and TCP send full class names, instead some ID.**

Im not sure if Netty already provide tool to change class names to ID, since:

`public ObjectDecoder(ClassResolver classResolver) {`

this Classes take ClassResolver, so would be worth look if can provide better classResolver here that will take ID only.

So in summary:
- when user do nothing - send full class names
- when user provide Class ID for each client/server, then use Special Class resolver sending only Class ID
(so when server see integer in ByteArray, use special class reslver for it)
- when client or server will be unable to match class by ID(if provided), throw error

What do you think?

see examples below of current packages:
(please note there is only one Class, but i already were sending more as fields, and each field send full class name)

```
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 00 00 00 b4 05 73 72 01 00 28 69 6f 2e 74 6c 66 |.....sr..(io.tlf|
> |00000010| 2e 6d 6f 6e 6b 65 79 6e 65 74 74 79 2e 6d 73 67 |.monkeynetty.msg|
> |00000020| 2e 55 64 70 43 6f 6e 48 61 73 68 4d 65 73 73 61 |.UdpConHashMessa|
> |00000030| 67 65 78 70 01 74 00 80 4c 22 3c 55 53 59 79 68 |gexp.t..L"<USYyh|
> |00000040| 5b 54 6f 2e 6e 53 4c 78 2a 46 3b 3c 25 51 74 25 |[To.nSLx*F;<%Qt%|
> |00000050| 58 37 2a 36 31 65 4f 27 79 40 39 59 62 44 3c 67 |X7*61eO'y@9YbD<g|
> |00000060| 7a 6c 5b 71 41 6c 5b 66 73 6d 46 7b 75 23 4e 55 |zl[qAl[fsmF{u#NU|
> |00000070| 76 69 3d 49 4d 7b 2f 52 30 72 2c 47 3e 59 26 74 |vi=IM{/R0r,G>Y&t|
> |00000080| 7d 2f 40 57 24 50 59 50 30 27 3f 38 3d 69 7a 7d |}/@W$PYP0'?8=iz}|
> |00000090| 6d 3e 2a 22 2d 36 2d 6e 32 76 4c 2f 74 31 48 55 |m>*"-6-n2vL/t1HU|
> |000000a0| 65 6b 64 5a 40 6f 2d 30 69 37 32 5f 3c 54 39 74 |ekdZ@o-0i72_<T9t|
> |000000b0| 51 40 7d 7a 7a 75 41 69                         |Q@}zzuAi        |
> +--------+-------------------------------------------------+----------------+
```

```
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 00 00 00 32 05 73 72 01 00 26 69 6f 2e 74 6c 66 |...2.sr..&io.tlf|
> |00000010| 2e 6d 6f 6e 6b 65 79 6e 65 74 74 79 2e 74 65 73 |.monkeynetty.tes|
> |00000020| 74 2e 54 65 73 74 54 43 50 4d 65 73 73 61 67 65 |t.TestTCPMessage|
> |00000030| 78 70 00 00 00 00                               |xp....          |
> +--------+-------------------------------------------------+----------------+
```

**Comment by oxplay2** [comment]
also, please note, i dont want make SpiderMonkey way that had issues, 

i think providing static class ID on both Client and Server will be better than sending Messages to register it.

**Comment by tlf30** [comment]
I will see what I can put together. It would be nice to use something native to java, perhaps the serialVersionUID? (https://www.baeldung.com/java-serial-version-uid) That way if the developer would like to add unique IDs, then they just implement the serialVersionUID, and then we do not have to attempt to sync the IDs between the server and client. 

For third party classes that fail to implement the serialVersionUID, I'm not sure on that yet, but it looks like only the containing class' name is sent (based on your examples) so as long as the developer adds the serialVersionUID to the message class it should not be an issue (I think, need to confirm). Most IDEs, provide a way to generate the serualVersionUID uniquely, and java serailization has a mechanism that auto generates the serial version uid bases on a base64 digest for when it is not provided by the developer, so maybe we can also utilize that.

**Comment by tlf30** [comment]
It looks like java automatically creates the serialVersionUID when it does not exist. The proper way to access it is
```
Class<?> clazz = obj.getClass();
Field f = clazz.getDeclraredField("serialVersionUID");
f.setAccessible(true);
long uid = (long)f.getValue();
```

**Comment by oxplay2** [comment]
yes, java create them automatically, **but each JVM might generate it different**, so assuming server would be on one JVM and Client on different JVM, we could get exception "local class incompatible".

Now question is, if Netty solved it own way to avoid this, or this is too much rare issue.

about:
> but it looks like only the containing class' name is sent (based on your examples)

Example yes, but i were earlier sending Entity over Netty and it had many String of class names send there.

I also think we should change to:

ClassResolvers.softCachingConcurrentResolver(null)

but im not sure what it cache exactly, but seems like it could speed up too.

Well i belive it will be my first stackoverflow question, since netty do not have Discord/Slack or anything.

https://stackoverflow.com/questions/64884218/objectencoder-objectdecoder-avoid-sending-full-class-name-within-message

Hope someone might know, then we will no need to search for a solution ourselfs.











https://github.com/netty/netty/pull/7303/commits/b484d5f81ed15edcf9ef6161038b5ba691e6ad79

**Comment by tlf30** [comment]
Yeah, the more I research the serialVersionUID, the more it looks not useful. It is not a unique class ID.

**Comment by oxplay2** [comment]
indeed, we need more research.

**Comment by tlf30** [comment]
So I opened a PR with an implementation: #11 

The basis of this implementation was to prevent the need to the developer to manually register messages or classes.

**Comment by oxplay2** [comment]
thats awesome! 

let me investigate it, first look is really nice :+1: 

one thing: could avoid dupplicated code via extending netty classes instead copy-paste 50% of them.

i will test it.

**Comment by tlf30** [comment]
> one thing: could avoid dupplicated code via extending netty classes instead copy-paste 50% of them.

I will look into that.

**Comment by tlf30** [comment]
It does not look like it, things like the CompactObjectInput/OutputStream which the NetworkMessageInput/OutputStream are modified versions of are not public: https://github.com/netty/netty/blob/8b2ed77042b5a3023974d7a6d2f22fc0d3edef34/codec/src/main/java/io/netty/handler/codec/serialization/CompactObjectInputStream.java#L25

I would rather create a modified copy than put more classes into the netty.io classpath. Especially considering they are not public, they are more likely to change and break the extension of them if we extend them. 

As for the NetworkMessageEncoder/Decoder, there is only a single method in each already, so there is little reason to extend the existing netty ones when they already extend from the same parent.

**Comment by oxplay2** [comment]
ok, 

the only reason not to do so, is if Netty will change their API or something else.

In this case i would suggest just add comment like:

/*
* This Class is modified version of: netty/codec/src/main/java/io/netty/handler/codec/serialization/CompactObjectInputStream.java
*/

for each file, to be able synchronize it with Netty later without "wonder" where it come from :)

**Comment by tlf30** [comment]
Closing, #11 was merged in.
