### ISSUE TITLE
Feature: Allow user override default message protocol

### ISSUE THREAD

**Issue by oxplay2** [tlf30/monkey-netty#7]
Currently Messages contain protocol within themselfs like:

```
    @Override
    public NetworkProtocol getProtocol() {
        return NetworkProtocol.TCP;
    }
```

My suggestion would be to:
1) change NetworkMessage as Abstract Class instead of Interface and add there a field for protocol, when provided, use it, when not, use default protocol method value

2) change "getProtocol" -> "getDefaultProtocol"

Question:
- Was there a reason it is hold by message itself? UDP reasons?

**Comment by tlf30** [comment]
This was how it was designed for The Outside Engine. The idea was that normally a message is only used in one channel or another, and normally the message "knows" which it should be in. For example a physics sync message (from outside):
```

package io.tlf.outside.network.message;


import io.tlf.outside.network.NetworkProtocol;

/**
 *
 * @author Trevor
 */

public class JmeSyncPhysicsObjectMessage implements NetworkMessage {

    protected int id;
    protected long timestap;
    //Position
    protected float x;
    protected float y;
    protected float z;
    //Rotation
    protected float i;
    protected float j;
    protected float k;
    //Velocity
    protected float vx;
    protected float vy;
    protected float vz;
    //Angular velocity
    protected float ri;
    protected float rj;
    protected float rk;
    //

    public JmeSyncPhysicsObjectMessage() {
    }
    
    @Override
    public String getName() {
        return "world-physics-sync-message";
    }

    @Override
    public NetworkProtocol getProtocol() {
        return NetworkProtocol.UDP;
    }

}
```
All (most) messages in the physics system are UDP. Then no matter what code calls the message, the message gets placed in the channel that it is expected to be in. 

For messages that want to be in either TCP or UDP, then we implement that setter at the per-message level:
```

package io.tlf.outside.network.message;

import io.tlf.outside.assets.MorphDelta;
import io.tlf.outside.network.NetworkProtocol;


/**
 *
 * @author Trevor
 */

public class JmeSyncMorphDeltaMessage implements NetworkMessage {

    private long id;
    private MorphDelta morphs;
    private NetworkProtocol protocol;

    public JmeSyncMorphDeltaMessage() {
    }

    @Override
    public String getName() {
        return "morph-sync-message";
    }

    public void setProtocol(NetworkProtocol protocol) {
        this.protocol = protocol;
    }
    
    @Override
    public NetworkProtocol getProtocol() {
        return protocol;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public MorphDelta getMorphs() {
        return morphs;
    }

    public void setMorphs(MorphDelta morphs) {
        this.morphs = morphs;
    }
}
```

The main reason behind this is when a large number of developers is working on a project, they may or may not know which channel the message needs to be in, but the developer who wrote the message most likely does. It also reduces the overhead of sending the protocol for every message.

**Comment by oxplay2** [comment]
ok got it. sounds ok, can close this feature then.
